name: Deployment

on: [workflow_dispatch, push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Run Lint
        run: npm run lint
      - name: Build code
        run: npm run build
      - name: Deploy
        run: echo "Deploying >>>"
